# Generated by Django 5.1.4 on 2024-12-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='total_seats',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
