# Generated by Django 5.1.4 on 2024-12-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='seats_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
