# Generated by Django 5.1.4 on 2024-12-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_train_seats_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='seats_reserved',
        ),
    ]
